import 'package:hive_flutter/hive_flutter.dart';
import 'hive_boxes.dart';

/// Hive initialization class
class HiveInit {
  /// Initialize Hive and register all adapters
  static Future<void> initialize() async {
    // Initialize Hive for Flutter
    await Hive.initFlutter();

    // Register all adapters - these will be auto-generated by hive_generator
    // The build_runner will create these adapters from model annotations
    // For now, we'll skip registration since generated adapters don't exist yet
    // In a real project, run: flutter pub run build_runner build

    // Open all boxes
    await HiveBoxes.openAllBoxes();
  }

  /// Close all Hive boxes
  static Future<void> close() async {
    await Hive.close();
  }
}


